"""Add preferences column to user table

Revision ID: 173e66b5b458
Revises: create_fts5_table
Create Date: 2025-11-10 22:32:09.753729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173e66b5b458'
down_revision = 'create_fts5_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###
