"""Initial migration with correct models

Revision ID: 719c62a13754
Revises: 
Create Date: 2025-09-20 15:11:38.871719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719c62a13754'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_trends')
    with op.batch_alter_table('trends', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trends', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_trends',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
