"""Add location field to articles

Revision ID: c27eb0aac537
Revises: 719c62a13754
Create Date: 2025-10-01 11:30:07.248091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c27eb0aac537'
down_revision = '719c62a13754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.drop_index('idx_article_date')
        batch_op.drop_index('idx_article_sentiment')
        batch_op.drop_index('idx_article_source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index('idx_article_source', ['source'], unique=False)
        batch_op.create_index('idx_article_sentiment', ['sentiment_label'], unique=False)
        batch_op.create_index('idx_article_date', ['date'], unique=False)
        batch_op.drop_column('location')

    # ### end Alembic commands ###
